# Generated by Django 6.0.7 on 2026-07-13 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0002_rename_address_line_1_companyaddress_address_line1_and_more'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='company_details.companydetails', verbose_name='Linked Client'),
        ),
        migrations.AddField(
            model_name='lead',
            name='ticket_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
