# Generated by Django 6.0.7 on 2026-07-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_invoicebankdetails_ifsc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebankdetails',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
