# Generated by Django 6.0.7 on 2026-07-13 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_department_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_credentials', to='categories.department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_credentials', to='categories.role')),
            ],
            options={
                'verbose_name': 'User Credential',
                'verbose_name_plural': 'User Credentials',
                'db_table': 'tbl_user_credential',
                'ordering': ['username'],
            },
        ),
    ]
