# Generated by Django 6.0.7 on 2026-07-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_usercredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceauthorizedperson',
            name='company_logo_sign',
            field=models.ImageField(upload_to='media/authorized_person_logo', verbose_name='Company Seal'),
        ),
        migrations.AlterField(
            model_name='invoiceauthorizedperson',
            name='person_sign',
            field=models.ImageField(upload_to='media/authorized_person', verbose_name='Person Sign'),
        ),
    ]
