# Generated by Django 6.0.7 on 2026-07-14 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0006_alter_invoiceauthorizedperson_company_logo_sign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, max_length=20)),
                ('task_type', models.CharField(choices=[('lead_handling', 'Lead Handling')], default='lead_handling', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('deadline_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned_by_me', to='categories.usercredential')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned_to_me', to='categories.usercredential')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assignments', to='categories.department')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignments', to='categories.role')),
            ],
            options={
                'db_table': 'tbl_task_assignment',
                'ordering': ['-assigned_at'],
                'unique_together': {('ticket_id', 'task_type')},
            },
        ),
    ]
