# Generated by Django 6.0.7 on 2026-07-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='deadline_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
