# Generated by Django 6.0.7 on 2026-07-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_invoiceauthorizedperson_company_logo_sign_and_more'),
        ('tasks', '0002_alter_taskassignment_deadline_hours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('reassigned', 'Reassigned')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['ticket_id', 'task_type', '-assigned_at'], name='tbl_task_as_ticket__e8e695_idx'),
        ),
    ]
