# Generated by Django 6.0.7 on 2026-07-14 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_details', '0002_rename_address_line_1_companyaddress_address_line1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=300)),
                ('client_campaign_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_order_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_type', models.CharField(max_length=50)),
                ('buying_type', models.CharField(max_length=60)),
                ('objective', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='company_details.companydetails')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'tbl_campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item_id', models.CharField(max_length=50, unique=True)),
                ('line_item_name', models.CharField(max_length=300)),
                ('ethnicity', models.JSONField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ad_format', models.JSONField()),
                ('impressions', models.BigIntegerField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=100, null=True)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('viewability', models.FloatField(blank=True, null=True)),
                ('vcr', models.FloatField(blank=True, null=True)),
                ('unit_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('kpi_notes', models.TextField(blank=True, null=True)),
                ('unit_value', models.FloatField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_targeting', models.TextField(blank=True, null=True)),
                ('dv_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('upcoming', 'Upcoming'), ('completed', 'Completed'), ('paused', 'Paused')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Line item',
                'verbose_name_plural': 'Line items',
                'db_table': 'tbl_line_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_name', models.CharField(max_length=300)),
                ('main_asset', models.FileField(blank=True, null=True, upload_to='creatives/main/')),
                ('dimensions', models.CharField(blank=True, max_length=50)),
                ('aspect_ratio', models.CharField(blank=True, max_length=20)),
                ('file_size', models.CharField(blank=True, max_length=30)),
                ('click_through_url', models.URLField(blank=True, max_length=400, null=True)),
                ('appended_html_tag', models.TextField(blank=True)),
                ('integration_code', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('creative_id', models.CharField(blank=True, max_length=100, null=True)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives_detail', to='campaigns.lineitem')),
            ],
            options={
                'verbose_name': 'Creative',
                'verbose_name_plural': 'Creatives',
                'db_table': 'tbl_creatives',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(blank=True, null=True, upload_to='thirdparty/files/')),
                ('backup_image', models.FileField(blank=True, null=True, upload_to='thirdparty/backup/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('creative_id', models.CharField(blank=True, max_length=100, null=True)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party_creatives', to='campaigns.lineitem')),
            ],
            options={
                'verbose_name': 'ThirdParty Creative',
                'verbose_name_plural': 'ThirdParty Creatives',
                'db_table': 'tbl_thirdparty_creative',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
