# Generated by Django 6.0.7 on 2026-07-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ticket_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
