# Generated by Django 6.0.7 on 2026-07-11 11:51

import company_details.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_invoicebankdetails_ifsc_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=100)),
                ('digital_signature', models.ImageField(blank=True, null=True, upload_to='company-user-signature')),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('zipcode', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_contact_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Contacts',
                'verbose_name_plural': 'Company Contacts',
                'db_table': 'tbl_company_contacts',
            },
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('report_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='Reporting ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('company_type', models.CharField(max_length=100)),
                ('agency_type', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=8)),
                ('billing_currency', models.CharField(default='INR', max_length=20)),
                ('gst_no', models.CharField(blank=True, max_length=40, null=True)),
                ('cin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('place_of_supply', models.CharField(blank=True, max_length=100)),
                ('credit_period_days', models.IntegerField()),
                ('is_domestic', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('Prepaid', 'Prepaid'), ('Postpaid', 'Postpaid')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('tax_type', models.CharField(max_length=50)),
                ('tds_applicable', models.BooleanField(default=False)),
                ('tds_section', models.CharField(max_length=50)),
                ('credit_limit', models.FloatField()),
                ('outstanding_limit', models.FloatField()),
                ('invoice_type', models.CharField(choices=[('single', 'Single Invoice'), ('multiple', 'Multiple Invoice')], default='single', max_length=20)),
                ('default_email_send_to', models.CharField(blank=True, max_length=500, null=True, validators=[company_details.models.validate_comma_separated_emails], verbose_name='Default Email To')),
                ('default_email_send_cc', models.CharField(blank=True, max_length=500, null=True, validators=[company_details.models.validate_comma_separated_emails], verbose_name='Default Email CC')),
                ('show_campaign_name_in_email', models.BooleanField(default=False, verbose_name='Campaign name display in the email')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('default_authorized_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.invoiceauthorizedperson', verbose_name='Authorized person')),
                ('default_contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_invoice_contact', to='company_details.companycontacts', verbose_name='Contact person')),
                ('default_invoice_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.invoicecompanyaddress', verbose_name='From company address')),
                ('default_invoice_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.invoicebankdetails', verbose_name='From bank account')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.paymentterms')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Details',
                'verbose_name_plural': 'Company Details',
                'db_table': 'tbl_company_details',
                'ordering': ['-client_id'],
            },
        ),
        migrations.AddField(
            model_name='companycontacts',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_details.companydetails'),
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('zipcode', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_details.companydetails')),
            ],
            options={
                'verbose_name': 'Company Address',
                'verbose_name_plural': 'Company Address',
                'db_table': 'tbl_company_address',
            },
        ),
    ]
