# Generated by Django 6.0.7 on 2026-07-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyaddress',
            old_name='address_line_1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='companyaddress',
            old_name='address_line_2',
            new_name='address_line2',
        ),
        migrations.RenameField(
            model_name='companycontacts',
            old_name='address_line_1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='companycontacts',
            old_name='address_line_2',
            new_name='address_line2',
        ),
        migrations.RenameField(
            model_name='companydetails',
            old_name='address_line_1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='companydetails',
            old_name='address_line_2',
            new_name='address_line2',
        ),
        migrations.RenameField(
            model_name='companydetails',
            old_name='cin_no',
            new_name='cin_number',
        ),
        migrations.RenameField(
            model_name='companydetails',
            old_name='gst_no',
            new_name='gst_number',
        ),
        migrations.RenameField(
            model_name='companydetails',
            old_name='payment_term',
            new_name='payment_terms',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='advance_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
